# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: ubuntu:latest

installation_dependency:
  cache:
    untracked: true
  only:
    refs:
      - dev
  script:
    - echo "installationing dependency..."
    - bash ./shell-script/installation_dependency.sh
    - bash ./shell-script/download-imagesbuilder.sh
    - bash ./shell-script/unzip_openwrt_imagebuilder.sh
    - echo "compileing openwrt..."
    - bash ./shell-script/compile_openwrt.sh
    - bash ./shell-script/zip_images.sh

  artifacts:
    paths:
      - openwrt_zip/

