# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker

stages:
  - setup
  - test
  - build

image: tangcuyu/openwrt-imagebuilder-x86-ubuntu:latest

cache:
  paths:
    - $BUILD_DIR/*


installation_dependency:
  stage: setup
  only:
    refs:
      - dev
  script:
    - echo "installationing dependency..."
    - pwd && ls -al
    - ls openwrt*.tar.xz || echo "axel -n 30 $DOWNLOAD_URL -o $BUILD_DIR/openwrt-imagebuilder-$OPENWRT_VERSION-$OPENWRT_PLATFORM-$OPENWRT_TARGETS.Linux-x86_64.tar.xz"
    - cd  $BUILD_DIR && ls openwrt*.tar.xz || axel -n 30 "https://downloads.openwrt.org/releases/$OPENWRT_VERSION/targets/$OPENWRT_PLATFORM/$OPENWRT_TARGETS/openwrt-imagebuilder-$OPENWRT_VERSION-$OPENWRT_PLATFORM-$OPENWRT_TARGETS.Linux-x86_64.tar.xz" && pwd 
    - pwd && ls -al && ls openwrt*.tar || xz -d "openwrt-imagebuilder-$OPENWRT_VERSION-$OPENWRT_PLATFORM-$OPENWRT_TARGETS.Linux-x86_64.tar.xz"
    - pwd && tar -xf "openwrt-imagebuilder-$OPENWRT_VERSION-$OPENWRT_PLATFORM-$OPENWRT_TARGETS.Linux-x86_64.tar"

make-info:
  stage: test
  only:
    refs:
      - dev
  script:
    - echo "make info..."
    - pwd && ls -al
    - cd $BUILD_DIR && ls -al && pwd
    - pwd && cd "openwrt-imagebuilder-$OPENWRT_VERSION-$OPENWRT_PLATFORM-$OPENWRT_TARGETS.Linux-x86_64" && ls -al && make info
    
compile:
  stage: build
  only:
    refs:
      - dev
  cache:
    paths:
      - openwrt_zip/*
  script:
    - echo "compileing openwrt..."
    - pwd && ls -al
    - cd $BUILD_DIR && ls al && pwd
    - pwd && cd "openwrt-imagebuilder-$OPENWRT_VERSION-$OPENWRT_PLATFORM-$OPENWRT_TARGETS.Linux-x86_64" && ls -al 
    - make image PROFILE=$BUILD_TARGETS PACKAGES="$PACKAGES"
    - mkdir -p ../../openwrt_zip/
    - ls -al ../../
    - mv $BIN_FILE/* ../../openwrt_zip/

  artifacts:
    paths:
      - openwrt_zip/

